name: Build Notebook Container

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    types: [opened, synchronize, reopened]
  release:
    types: [published]
  workflow_dispatch:

jobs:
  build:
    permissions:
      statuses: write 
    runs-on: ubuntu-latest
    steps:

    - name: checkout files in repo
      uses: actions/checkout@v3

    - name: cache binder build on mybinder.org
      uses: jupyterhub/repo2docker-action@master
      with:
        NO_PUSH: true
        MYBINDERORG_TAG: ${{ github.event.ref }}

    - name: Report URL
      if: success() && github.event_name == 'pull_request'
      continue-on-error: True
      uses: Sibz/github-status-action@v1
      with: 
        authToken: ${{secrets.GITHUB_TOKEN}}
        context: 'openff-toolkit on Binder'
        description: 'Launch the Toolkit examples on Binder'
        state: 'success'
        sha: ${{github.event.pull_request.head.sha || github.sha}}
        target_url: https://mybinder.org/v2/gh/${{ github.repository }}/${{ github.event.pull_request.head.ref }}?urlpath=git-pull%3Frepo%3Dhttps%253A%252F%252Fgithub.com%252Fopenforcefield%252Fopenff-toolkit%26urlpath%3Dlab%252Ftree%252Fopenff-toolkit%252Fexamples%26branch%3Dmain

